-- Additive, isolated application schema. Existing Pixelalty objects are untouched.
create schema px_private;
revoke all on schema px_private from public, anon;
grant usage on schema px_private to authenticated, service_role;
alter default privileges in schema px_private revoke execute on functions from public;

create table public.px_roles(user_id uuid not null references auth.users(id),role text not null check(role in ('owner','sales_admin','manager','finance_admin','compliance_admin','content_admin','support')),primary key(user_id,role));
create table public.px_teams(id uuid primary key default gen_random_uuid(),name text not null,manager_id uuid references auth.users(id));
create sequence px_private.rep_codes;
create table public.px_reps(id uuid primary key references auth.users(id),code text not null unique default ('PXL-'||lpad(nextval('px_private.rep_codes')::text,5,'0')),name text not null,timezone text not null default 'UTC',status text not null default 'onboarding' check(status in ('onboarding','active','suspended','offboarded')),team_id uuid references public.px_teams(id),capacity int not null default 10 check(capacity between 1 and 100),bio text not null default '',income_goal int not null default 0 check(income_goal>=0),preferences jsonb not null default '{}',created_at timestamptz not null default now());
create table public.px_rep_private(rep_id uuid primary key references public.px_reps(id),email text not null,classification text not null default 'unconfigured' check(classification in ('unconfigured','contractor','employee')),tax_status text not null default 'pending' check(tax_status in ('pending','verified')),external_payout_verified boolean not null default false);
create sequence px_private.app_codes;
create table public.px_applicants(id uuid primary key default gen_random_uuid(),code text unique not null default ('APP-'||lpad(nextval('px_private.app_codes')::text,6,'0')),email text not null,name text not null,details jsonb not null,stage text not null default 'new' check(stage in ('new','review','interview','offer','approved','rejected','approval_error')),rep_id uuid references public.px_reps(id),created_at timestamptz not null default now());
create unique index px_app_email on public.px_applicants(lower(email));
create table public.px_applicant_notes(id uuid primary key default gen_random_uuid(),applicant_id uuid not null references public.px_applicants(id),author_id uuid not null references auth.users(id),body text not null check(length(body) between 1 and 5000),created_at timestamptz not null default now());
create table public.px_settings(id boolean primary key default true check(id),value jsonb not null);
insert into public.px_settings values(true,'{"hold_days":7,"claim_count":10,"first_attempt_hours":48,"ownership_days":14,"calling_enabled":false,"call_start":9,"call_end":17,"raw_xp_cap":50,"recruiting_open":true,"auto_transfers":false,"require_agreement":true,"require_tax":true,"require_payout":true}');
create table public.px_packages(id uuid primary key default gen_random_uuid(),code text not null,name text not null,version int not null check(version>0),price_cents int not null check(price_cents>0),commission_cents int not null check(commission_cents>=0 and commission_cents<=price_cents),sale_xp int not null check(sale_xp>=0),active boolean not null default true,created_at timestamptz not null default now(),unique(code,version));
create unique index px_package_active on public.px_packages(code) where active;
insert into public.px_packages(code,name,version,price_cents,commission_cents,sale_xp) values('launch','Launch',1,79900,12500,100),('growth','Growth',1,129900,25000,150),('premium','Premium',1,199900,40000,225),('advanced','Advanced',1,299900,60000,300);
create table public.px_content(id uuid primary key default gen_random_uuid(),kind text not null check(kind in ('lesson','quiz','script','knowledge','announcement','agreement')),slug text not null,title text not null,body text not null,version int not null default 1,required boolean not null default false,active boolean not null default true,created_at timestamptz not null default now(),unique(kind,slug,version));
create unique index px_content_active on public.px_content(kind,slug) where active;
create table px_private.quiz_keys(content_id uuid primary key references public.px_content(id),answers jsonb not null);
create table public.px_training(id uuid primary key default gen_random_uuid(),rep_id uuid not null references public.px_reps(id),content_id uuid not null references public.px_content(id),score int check(score between 0 and 100),passed boolean not null default true,created_at timestamptz not null default now());
create index px_training_rep on public.px_training(rep_id,content_id);
create table public.px_agreements(id uuid primary key default gen_random_uuid(),rep_id uuid not null references public.px_reps(id),content_id uuid not null references public.px_content(id),signature text not null,created_at timestamptz not null default now(),unique(rep_id,content_id));
create table public.px_imports(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id),filename text not null,mapping jsonb not null,status text not null default 'staging' check(status in ('staging','ready','complete','archived')),total int not null check(total between 1 and 25000),created_at timestamptz not null default now());
create table public.px_import_rows(batch_id uuid not null references public.px_imports(id),row_num int not null,data jsonb not null,error text,status text not null default 'pending' check(status in ('pending','accepted','rejected')),primary key(batch_id,row_num));
create table public.px_saved_views(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id),name text not null,kind text not null,config jsonb not null,created_at timestamptz not null default now());
create sequence px_private.business_codes;
create table public.px_businesses(id uuid primary key default gen_random_uuid(),code text not null unique default ('BIZ-'||lpad(nextval('px_private.business_codes')::text,7,'0')),name text not null check(length(name) between 1 and 200),phone text not null check(phone~'^\+[0-9]{11,15}$'),domain text not null default '',email text not null default '',timezone text not null,city text not null default '',state text not null default '',industry text not null default '',contact text not null default '',notes text not null default '',stage text not null default 'new' check(stage in ('new','working','interested','follow_up','meeting','proposal','won','lost','dnc')),owner_id uuid references public.px_reps(id),claimed_at timestamptz,expires_at timestamptz,first_attempt_at timestamptz,dnc boolean not null default false,customer boolean not null default false,archived boolean not null default false,import_id uuid references public.px_imports(id),created_at timestamptz not null default now());
create unique index px_business_phone on public.px_businesses(phone);
create unique index px_business_domain on public.px_businesses(domain) where domain<>'';
create index px_business_owner on public.px_businesses(owner_id,expires_at);
create index px_business_claimable on public.px_businesses(created_at) where owner_id is null and not dnc and not customer and not archived;
create table public.px_dnc(id uuid primary key default gen_random_uuid(),phone text not null,reason text not null,active boolean not null default true,actor_id uuid references auth.users(id),created_at timestamptz not null default now());
create unique index px_dnc_phone on public.px_dnc(phone) where active;
create table public.px_assignments(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.px_businesses(id),rep_id uuid not null references public.px_reps(id),action text not null,actor_id uuid references auth.users(id),created_at timestamptz not null default now());
create table public.px_calls(id uuid primary key default gen_random_uuid(),request_id uuid not null unique,rep_id uuid not null references public.px_reps(id),business_id uuid not null references public.px_businesses(id),outcome text not null check(outcome in ('no_answer','voicemail','gatekeeper','conversation','interested','follow_up','meeting','proposal','not_interested','wrong_number','disconnected','do_not_call','sale_reported')),notes text not null default '' check(length(notes)<=5000),script_id uuid references public.px_content(id),created_at timestamptz not null default now());
create index px_calls_rep on public.px_calls(rep_id,created_at desc);
create index px_calls_business on public.px_calls(business_id,created_at desc);
create table public.px_followups(id uuid primary key default gen_random_uuid(),rep_id uuid not null references public.px_reps(id),business_id uuid not null references public.px_businesses(id),due_at timestamptz not null,timezone text not null,note text not null default '',status text not null default 'open' check(status in ('open','complete','cancelled')),notified_at timestamptz,created_at timestamptz not null default now());
create index px_followups_due on public.px_followups(rep_id,due_at) where status='open';
create sequence px_private.deal_codes;
create table public.px_deals(id uuid primary key default gen_random_uuid(),code text not null unique default ('DEAL-'||lpad(nextval('px_private.deal_codes')::text,7,'0')),rep_id uuid not null references public.px_reps(id),business_id uuid not null references public.px_businesses(id),package_id uuid not null references public.px_packages(id),package_name text not null,price_cents int not null check(price_cents>0),commission_cents int not null check(commission_cents>=0 and commission_cents<=price_cents),sale_xp int not null,currency text not null default 'usd' check(currency='usd'),stage text not null default 'proposal' check(stage in ('proposal','checkout','paid','cancelled')),customer_email text not null,checkout_id text unique,checkout_url text,created_at timestamptz not null default now());
create index px_deals_rep on public.px_deals(rep_id,created_at desc);
create table public.px_connect(rep_id uuid primary key references public.px_reps(id),account_id text not null unique,transfers_enabled boolean not null default false,payouts_enabled boolean not null default false,details_submitted boolean not null default false,requirements jsonb not null default '[]',checked_at timestamptz not null default now());
create table public.px_payments(id uuid primary key default gen_random_uuid(),deal_id uuid not null unique references public.px_deals(id),payment_intent text not null unique,charge_id text not null unique,amount_cents int not null check(amount_cents>0),refunded_cents int not null default 0 check(refunded_cents>=0 and refunded_cents<=amount_cents),disputed boolean not null default false,settled boolean not null default false,available_at timestamptz,created_at timestamptz not null default now());
create table public.px_commissions(id uuid primary key default gen_random_uuid(),deal_id uuid not null unique references public.px_deals(id),rep_id uuid not null references public.px_reps(id),amount_cents int not null check(amount_cents>=0),status text not null default 'hold' check(status in ('hold','payable','queued','transferred','recovery_review','reversed')),hold_until timestamptz not null,manual_hold boolean not null default false,transfer_id text unique,reversed_cents int not null default 0 check(reversed_cents>=0 and reversed_cents<=amount_cents),created_at timestamptz not null default now());
create index px_commissions_rep on public.px_commissions(rep_id,created_at desc);
create table public.px_commission_events(id uuid primary key default gen_random_uuid(),commission_id uuid not null references public.px_commissions(id),event text not null,amount_cents int not null default 0,external_id text unique,reason text not null,actor_id uuid references auth.users(id),created_at timestamptz not null default now());
create table public.px_transfer_requests(id uuid primary key default gen_random_uuid(),commission_id uuid not null unique references public.px_commissions(id),status text not null default 'pending' check(status in ('pending','complete','uncertain')),transfer_id text,created_at timestamptz not null default now());
create table public.px_payouts(id text primary key,rep_id uuid not null references public.px_reps(id),amount_cents int not null,currency text not null,status text not null,arrival_at timestamptz,updated_at timestamptz not null default now());
create table public.px_stripe_events(id text primary key,type text not null,status text not null,error text,created_at timestamptz not null default now());
create table public.px_fulfillment(id uuid primary key default gen_random_uuid(),deal_id uuid not null unique references public.px_deals(id),status text not null default 'new',notes text not null default '',created_at timestamptz not null default now());
create table public.px_xp(id uuid primary key default gen_random_uuid(),rep_id uuid not null references public.px_reps(id),source text not null,source_id uuid not null,amount int not null check(amount>=0),created_at timestamptz not null default now(),unique(rep_id,source,source_id));
create index px_xp_rep on public.px_xp(rep_id,created_at desc);
create table public.px_notifications(id uuid primary key default gen_random_uuid(),rep_id uuid not null references public.px_reps(id),title text not null,body text not null,read_at timestamptz,created_at timestamptz not null default now());
create table public.px_support(id uuid primary key default gen_random_uuid(),rep_id uuid not null references public.px_reps(id),subject text not null,body text not null,status text not null default 'open',reply text,created_at timestamptz not null default now());
create table public.px_audit(id uuid primary key default gen_random_uuid(),actor_id uuid references auth.users(id),action text not null,target_id text,reason text not null default '',details jsonb not null default '{}',created_at timestamptz not null default now());
create table px_private.rate_limits(key text primary key,started_at timestamptz not null default now(),count int not null default 1);

create function px_private.has_role(roles text[]) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and coalesce(auth.jwt()->>'aal','')='aal2' and exists(select 1 from public.px_roles where user_id=auth.uid() and (role='owner' or role=any(roles))); $$;
create function px_private.active() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.px_reps where id=auth.uid() and status='active'); $$;
create function px_private.team_scope(rep uuid) returns boolean language sql stable security definer set search_path='' as $$ select px_private.has_role(array['manager']) and exists(select 1 from public.px_reps r join public.px_teams t on t.id=r.team_id where r.id=rep and t.manager_id=auth.uid()); $$;
create function px_private.require_role(roles text[]) returns void language plpgsql security definer set search_path='' as $$ begin if not px_private.has_role(roles) then raise exception 'An authorized administrator with MFA is required.' using errcode='42501';end if;end; $$;
create function px_private.audit(action text,target text,reason text default '',details jsonb default '{}') returns void language sql security definer set search_path='' as $$ insert into public.px_audit(actor_id,action,target_id,reason,details) values(auth.uid(),action,target,reason,details); $$;
create function px_private.immutable() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'This record is append-only.';end; $$;
create function px_private.valid_timezone(zone text) returns boolean language sql stable set search_path='' as $$ select exists(select 1 from pg_catalog.pg_timezone_names where name=zone); $$;
grant execute on function px_private.has_role(text[]),px_private.active(),px_private.team_scope(uuid) to authenticated;

do $$ declare n text; begin
 for n in select tablename from pg_tables where schemaname='public' and tablename like 'px_%' loop
  execute format('alter table public.%I enable row level security',n);
  execute format('revoke all on public.%I from anon,authenticated',n);
  execute format('grant select on public.%I to authenticated',n);
  execute format('grant all on public.%I to service_role',n);
 end loop;
 for n in select tablename from pg_tables where schemaname='px_private' loop execute format('alter table px_private.%I enable row level security',n);end loop;
 foreach n in array array['px_audit','px_calls','px_xp','px_commission_events','px_training','px_agreements','px_assignments'] loop
  execute format('create trigger append_only before update or delete on public.%I for each row execute function px_private.immutable()',n);
 end loop;
end $$;
create policy roles_read on public.px_roles for select to authenticated using(user_id=(select auth.uid()) or px_private.has_role(array['owner']));
create policy teams_read on public.px_teams for select to authenticated using(manager_id=(select auth.uid()) or px_private.has_role(array['sales_admin']));
create policy reps_read on public.px_reps for select to authenticated using(id=(select auth.uid()) or px_private.team_scope(id) or px_private.has_role(array['sales_admin','support']));
create policy private_read on public.px_rep_private for select to authenticated using(rep_id=(select auth.uid()) or px_private.has_role(array['sales_admin','compliance_admin']));
create policy applicants_read on public.px_applicants for select to authenticated using(px_private.has_role(array['sales_admin']));
create policy app_notes_read on public.px_applicant_notes for select to authenticated using(px_private.has_role(array['sales_admin']));
create policy settings_read on public.px_settings for select to authenticated using(auth.uid() is not null);
create policy packages_read on public.px_packages for select to authenticated using(auth.uid() is not null);
create policy content_read on public.px_content for select to authenticated using(exists(select 1 from public.px_reps where id=auth.uid()) or px_private.has_role(array['content_admin']));
create policy training_read on public.px_training for select to authenticated using(rep_id=(select auth.uid()) or px_private.team_scope(rep_id) or px_private.has_role(array['sales_admin','content_admin']));
create policy agreements_read on public.px_agreements for select to authenticated using(rep_id=(select auth.uid()) or px_private.has_role(array['compliance_admin','sales_admin']));
create policy imports_read on public.px_imports for select to authenticated using(px_private.has_role(array['sales_admin']));
create policy import_rows_read on public.px_import_rows for select to authenticated using(px_private.has_role(array['sales_admin']));
create policy views_read on public.px_saved_views for select to authenticated using(owner_id=(select auth.uid()));
create policy businesses_read on public.px_businesses for select to authenticated using((owner_id=(select auth.uid()) and px_private.active()) or px_private.team_scope(owner_id) or px_private.has_role(array['sales_admin','compliance_admin']));
create policy dnc_read on public.px_dnc for select to authenticated using(px_private.has_role(array['sales_admin','compliance_admin']));
create policy assignments_read on public.px_assignments for select to authenticated using((rep_id=(select auth.uid()) and px_private.active()) or px_private.team_scope(rep_id) or px_private.has_role(array['sales_admin','compliance_admin']));
create policy calls_read on public.px_calls for select to authenticated using((rep_id=(select auth.uid()) and px_private.active()) or px_private.team_scope(rep_id) or px_private.has_role(array['sales_admin','compliance_admin']));
create policy followups_read on public.px_followups for select to authenticated using((rep_id=(select auth.uid()) and px_private.active()) or px_private.team_scope(rep_id) or px_private.has_role(array['sales_admin','compliance_admin']));
create policy deals_read on public.px_deals for select to authenticated using((rep_id=(select auth.uid()) and px_private.active()) or px_private.team_scope(rep_id) or px_private.has_role(array['sales_admin','finance_admin']));
create policy connect_read on public.px_connect for select to authenticated using(rep_id=(select auth.uid()) or px_private.has_role(array['finance_admin','sales_admin']));
create policy payments_read on public.px_payments for select to authenticated using(px_private.has_role(array['finance_admin']));
create policy commissions_read on public.px_commissions for select to authenticated using(rep_id=(select auth.uid()) or px_private.has_role(array['finance_admin']));
create policy commission_events_read on public.px_commission_events for select to authenticated using(exists(select 1 from public.px_commissions c where c.id=commission_id and c.rep_id=auth.uid()) or px_private.has_role(array['finance_admin']));
create policy transfer_read on public.px_transfer_requests for select to authenticated using(px_private.has_role(array['finance_admin']));
create policy payouts_read on public.px_payouts for select to authenticated using(rep_id=(select auth.uid()) or px_private.has_role(array['finance_admin']));
create policy events_read on public.px_stripe_events for select to authenticated using(px_private.has_role(array['finance_admin']));
create policy fulfillment_read on public.px_fulfillment for select to authenticated using(px_private.has_role(array['sales_admin','support']));
create policy xp_read on public.px_xp for select to authenticated using(rep_id=(select auth.uid()) or px_private.team_scope(rep_id) or px_private.has_role(array['sales_admin']));
create policy notifications_read on public.px_notifications for select to authenticated using(rep_id=(select auth.uid()));
create policy support_read on public.px_support for select to authenticated using(rep_id=(select auth.uid()) or px_private.has_role(array['support']));
create policy audit_read on public.px_audit for select to authenticated using(px_private.has_role(array['owner']));
